apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-sc-test
spec:
  storageClassName: sc-test
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: sc-test-pod
  labels:
    app.kubernetes.io/name: web-app
spec:
  containers:
  - name: web-app
    image: nginx
    ports:
      - containerPort: 80
    volumeMounts:
    - name: sc-rancher
      mountPath: /var/log/nginx
      
  volumes:
  - name: sc-rancher
    persistentVolumeClaim:
      claimName: pvc-sc-test