apiVersion: v1
kind: Pod
metadata:
  name: busibox-pod
  labels:
    app.kubernetes.io/name: busyapp
spec:
  containers:
  - name: busybox-cont
    image: busybox
    command: ["sleep", "600"]
  - name: nginx-cont
    image: nginx:1.24
