apiVersion: apps/v1
kind: ReplicaSet
metadata: # labels for the replicaset
  name: rs-demo-2
  labels:
    app: rs
    env: rs
    project: robostore
  annotations:
    imageRestry: "https://k8s.io/"
spec:
  replicas: 3
  selector: # This is the selecting criteria for replicaset to pick the pods with following selector labels
    matchLabels:
      app: web
      env: testing
      project: roboshop
  template: #This is the pod definition, labels under this section will be applied to pod
    metadata:
      labels:
        project: roboshop
        app: web
        env: testing
    spec:
      containers:
        - name: nginx
          image: nginx:1.24