apiVersion: v1
kind: Pod
metadata:
  name: resource-demo
  labels:
    app.kubernetes.io/name: resource-demo
spec:
  containers:
  - name: resource-demo
    image: curlimages/curl
    command: ["ping", "localhost"]
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
