apiVersion: v1
kind: Secret
metadata:
  name: test-secret
type: Opaque
data:
  username: YWRtaW4K
  password: YWRtaW5AMTIzCg==
  
  .secrets: |
    SWYgeW91IGFyZSBjcmVhdGluZyBhIFNlY3JldCB0byBzdG9yZSBjcmVkZW50aWFscyBmb3IgYWNj
    ZXNzaW5nIGEgY29udGFpbmVyIGltYWdlIHJlZ2lzdHJ5LCB5b3UgbXVzdCB1c2Ugb25lIG9mIHRo
    ZSBmb2xsb3dpbmcgdHlwZSB2YWx1ZXMgZm9yIHRoYXQgU2VjcmV0Ogo=

      