apiVersion: v1
kind: Pod
metadata:
  name: secret-pod-file
  labels:
    app.kubernetes.io/name: secret-pod-file
spec:
  containers:
  - name: secret-pod-file
    image: nginx
    resources:
      requests:
        cpu: "250m"
        memory: "64Mi"
      limits:
        memory: "128Mi"
        cpu: "500m"
    volumeMounts:
    - name:  secret-vol
      mountPath:  /home/secrets
      readOnly: true
  volumes:
  - name:  secret-vol
    secret:
      secretName: test-secret
      