apiVersion: v1
kind: Pod
metadata:
  name: secret-pod-valuefrom
  labels:
    app.kubernetes.io/name: secret-pod-valuefrom
spec:
  containers:
  - name: secret-pod-valuefrom
    image: nginx
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"   
    env:
    - name: SECRET
      valueFrom:
        secretKeyRef:
          name: test-secret
          key: .secrets