apiVersion: v1
kind: Service
metadata:
  name: sts-svc
spec:
  clusterIP: None
  selector:
    app: web-app
    env: dev
  ports:
  - name: mysql
    port: 3306
    targetPort: 3306
---
apiVersion: apps/v1
kind: StatefulSet
metadata: 
  name: sts-test
  labels: 
    app: web-app
    env: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-app
      env: dev
  template:
    metadata:
      labels:
        app: web-app
        env: dev
    spec:
      containers:
      - name: mysql
        image: mrmotam/mysql:v1
        args: ["--mysql-native-password=ON"]
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "RoboShop@1"
        ports:
        - name: mysql
          containerPort: 3306
  serviceName: sts-svc
  volumeClaimTemplates:
  - metadata:
      name: mysql-www
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: sc-test
      resources:
        requests:
          storage: 2Gi