apiVersion: v1
kind: Pod
metadata:
  name: simple-pod
spec:
  containers:
    - name: busybox-test
      image:  busybox
      command:
        - sleep
        - "3600"
      resources:
        requests:
          cpu: "100m"
          memory: "128Mi"
        limits:
          cpu: "150m"
          memory: "256Mi"